oauth2:
  logout-redirect-uri: https://auth.niq-dev.com/oidc/logout?post_logout_redirect_uri=https://portal.niq-dev.com/
  api-uri: https://auth.niq-dev.com/api/auth/hello

spring:
  data: 
    redis:
      host: niq-dev.com
      port: 6380
      password: ${RD_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          portal-client:
            client-id: portal-client
            client-secret: portal-secret
            authorization-grant-type: authorization_code
            redirect-uri: https://portal.niq-dev.com/login/oauth2/code/portal-client
            scope: openid,read
            provider: portal-client-provider
        provider:
          portal-client-provider:
            issuer-uri: https://auth.niq-dev.com
